---
# Plex media server install

# set-up nfs
# certbot
# http://localhost:32400/web.
# sudo apt upgrade plexmediaserver -y


- name: Add Plex APT Key
  apt_key:
    url: "https://downloads.plex.tv/plex-keys/PlexSign.key"
    state: present

- name: Add the Plex APT Repo
  apt_repository:
    repo: "https://downloads.plex.tv/repo/deb public main"
    state: present

- name: Install Plex Media Server
  apt:
    name: plexmediaserver
    state: latest
    update_cache: yes
    notify: 'restart-ansible-role-plex'

- name: 'Start the plexmediaserver daemon'
  service:
    name: 'plexmediaserver'
    state: 'started'
    enabled: 'yes'


# defaults/main.yml
# plex_app_transcode_directory: '/opt/plex_transcode'
# plex_app_library_directory: '/opt/plex_library'
