---
- name: 'restart-ansible-role-plex'
  become: true
  service:
    name: 'plexmediaserver'
    state: 'restarted'

- name: 'restart-nginx-role-plex'
  become: true
  service:
    name: 'nginx'
    state: 'restarted'
